### PR TITLE
Display items

### PR DESCRIPTION
**Pull request by tumainimaganiko**
In this project, I did the following:

- When the page loads, the web app retrieves data from the API
- Displaying the list of items on the homepage 
- Created and used modular JavaScript
- Follow git-flow

### CODE REVIEW

**Comment by Paul-tes** [comment]
## Hi @tumainimaganiko You are very good with working with these Project.
> I suggest you to change listed below.

- [ ] Create the main part of the homepage that keeps the layout from the wireframe: The comment and reservation shold be button.
c1
_Optional_ listed in the comment section bellow.

- [ ] try to add simple logo on the header.

**Review by Paul-tes — COMMENTED** [review]
- add id attribute with the value of the id number of the item that passed though in the argument to the div element that wrapes the item img, comment and reservation. it will make easy to capture the event to the specific element.

**Comment by tumainimaganiko** [comment]
Thanks for the feedback. I have implemented the requested changes kindly check them to verify.

**Comment by Paul-tes** [comment]
Hi @tumainimaganiko 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Linters are passing 👍 
The project is running successfully 👍 
PR is well descriptive 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@paul-tes** in your question so I can receive the notification.

------

**Pull request merged**
